apiVersion: v1
kind: Service
metadata:
  name: mycms-be2-svc
spec:
  selector:
    app: mycms-be
    version: v2
  type: LoadBalancer
  ports:
  - port:  80
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycms-be-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycms-be
  template:
    metadata:
      labels:
        app: mycms-be
        zone: prod
        version: v2
    spec:
      containers:
        - name: mycms
          image:  apomic80/mycms-be:v2
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: DEVELOPMENT
            - name: SA_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mssql
                  key: SA_PASSWORD 
            - name: SQLSERVER_CONNECTIONSTRING
              value: "Server=db-sqlserver-svc;Database=mycms;User=sa;Password={password};MultipleActiveResultSets=true;"
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password 
            - name: RABBIT_USER
              value: "user"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_HOSTNAME
              value: "rabbitmq.default.svc.cluster.local"
