apiVersion: apps/v1
kind: Deployment
metadata:
  name: mycms-denormalizer-redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mycms-denormalizer-redis
  template:
    metadata:
      labels:
        app: mycms-denormalizer-redis
        zone: prod
        version: v1
    spec:
      containers:
        - name: mycms-denormalizer-redis
          image: apomic80/mycms-denormalizer-redis:v1
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          env:
            - name: ASPNETCORE_ENVIRONMENT
              value: DEVELOPMENT
            - name: RABBIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: rabbitmq
                  key: rabbitmq-password
            - name: RABBIT_USER
              value: "user"
            - name: RABBIT_PORT
              value: "5672"
            - name: RABBIT_HOSTNAME
              value: "rabbitmq.default.svc.cluster.local"
            - name: FRONTEND_QUEUE_NAME
              value: "frontend"
            - name: REDIS_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: redis
                  key: redis-password
            - name: REDIS_CONNECTIONSTRING
              value: "redis-slave.default.svc.cluster.local:6379,password={password},ssl=False,abortConnect=False"
